dataset<-read.csv("raw_data.csv")
dataset<-dataset%>%filter(Personspersleepingroom!='Dont know/missing')
library(pointblank)
test_col_is_character(dataset,Characteristic)
test_col_vals_not_null(dataset,Characteristic)
test_col_is_character(dataset,Electricity)
test_col_vals_not_null(dataset,Electricity)
test_col_is_character(dataset,Sourceofdrinkingwater)
test_col_vals_not_null(dataset,Sourceofdrinkingwater)
test_col_is_character(dataset,Timetowatersource)
test_col_vals_not_null(dataset,Timetowatersource)
test_col_is_character(dataset,Sanitationfacility)
test_col_vals_not_null(dataset,Sanitationfacility)
test_col_is_character(dataset,Flooring)
test_col_vals_not_null(dataset,Flooring)
test_col_is_character(dataset,Personspersleepingroom)
test_col_vals_not_null(dataset,Personspersleepingroom)
write.csv(dataset,"cleaned_data.csv")